name: 'Deploy to S3 using docker'
description: 'Docker version of s3 deploy'
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true
  region:
    description: 'The S3 bucket name'
    required: false
    default: 'us-east-1'
  folder:
    description: 'The folder path within the bucket'
    required: true
    default: 'dist'
runs:
  using: 'docker'
  # use locally defined docker image
  image: 'Dockerfile'
