name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Fetch and Cache dependencies
        id: fetch
        uses: ./.github/actions/cached-deps
        with:
          ignore-cache: 'true'
      - name: Cache Usage Status
        run: echo "cache usage was ${{ steps.fetch.outputs.status-cache-use }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Fetch and Cache dependencies
        id: fetch
        uses: ./.github/actions/cached-deps
      - name: Cache Usage Status
        run: echo "cache usage was ${{ steps.fetch.outputs.status-cache-use }}"
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Fetch and Cache dependencies
        id: fetch
        uses: ./.github/actions/cached-deps
      - name: Cache Usage Status
        run: echo "cache usage was ${{ steps.fetch.outputs.status-cache-use }}"
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deployJS:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        id: deploy2s3
        uses: ./.github/actions/deploy-s3-javascript
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: nosuchbucket
          folder: ./dist
      - name: output live url
        run: |
          echo "Live URL is ${{ steps.deploy2s3.outputs.website-url }}"
  deployDocker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        id: deploy2docker
        uses: ./.github/actions/deploy-s3-docker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: nosuchbucket2
          folder: ./dist
      - name: output live url
        run: |
          echo "Live URL is ${{ steps.deploy2docker.outputs.website-url }}"
